### ISSUE TITLE
model.get_layer('mirna').output_shape

### ISSUE THREAD

**Issue by ghost** [amlantalukder/DMISO#1]
Good afternoon.
I've tried running DMISO with the example data:

`python3 dmiso.py -t examples/test_mRNAs.fa -m examples/test_miRNAs.fa`

But the following error appeared:

```
Loaded model from disk
Traceback (most recent call last):
  File "***/bin/DMISO/dmiso.py", line 156, in <module>
    _, len_mirna, _ = model.get_layer('mirna').output_shape
ValueError: not enough values to unpack (expected 3, got 1)
```

dmiso.py at line 156, if I'm not mistaken, is basically loading the model from the json file `model_top.json` but I still don't understand which values the program is referring to (expected 3, got 1) while looking at the json file

I'm using Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0] on linux.
Tensorflow version 2.10.0

**Comment by RJEGR** [comment]
Hi everyone,

I got the same issue with the model.get_layer.  Any solution?

Ubuntu 20.04
Python 3.8.10
keras==2.11.0
more-itertools==4.2.0
numpy==1.24.2
scikit-learn==1.2.2
tensorflow==2.11.0
tensorflow-cpu==2.11.0

```
Traceback (most recent call last):
  File "./dmiso.py", line 156, in <module>
    _, len_mirna, _ = model.get_layer('mirna').output_shape
ValueError: not enough values to unpack (expected 3, got 1)
```

**Comment by amlantalukder** [comment]
Hello,

Thanks for pointing this issue. This issue was due to incompatible version of a specific package. I have now provided a detailed requirement list and updated the installation procedure in the readme. Follow this (also in the README.md).

1. Install python version 3.7 or higher
2. Run the following to install necessary python packages
  ```
  cd DMISO
  make all
  ```
